// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrhektgjhalqlvaoystm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyaGVrdGdqaGFscWx2YW95c3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzg2MzMsImV4cCI6MjA2NDkxNDYzM30.ZSbszo9vn0Nxr439KPvfbMcWOX-P4IRB7jy-j97tUwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);